#name: Java CICD with Gradle DEPRECATED
#
#on:
#  push:
#    branches:
#      - 'develop'
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#
#      - name: Create application.yml
#        run: |
#          mkdir ./src/main/resources
#          touch ./src/main/resources/application.yml
#          echo "${{ secrets.APPLICATION_YML }}" >> ./src/main/resources/application.yml
#
#      - name: Create application-dev.yml
#        run: |
#          touch ./src/main/resources/application-dev.yml
#          echo "${{ secrets.APPLICATION_DEV_YML }}" >> ./src/main/resources/application-dev.yml
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x ./gradlew
#
#      - name: Build with Gradle
#        run: ./gradlew build
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{secrets.DOCKERHUB_USERNAME}}
#          password: ${{secrets.DOCKERHUB_TOKEN}}
#
#      - name: Build the Docker image
#        run: docker build --platform linux/amd64 --build-arg DEPENDENCY=build/dependency -f DockerfileDev -t ${{secrets.DOCKERHUB_USERNAME}}/dotori-dev .
#
#      - name: Docker Push
#        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/dotori-dev
