name: Dotori Develop Server CD

on:
  push:
    branches: [ develop ]

env:
  S3_BUCKET_NAME: dotori-deploy-bucket
  PROJECT_NAME: Dotori_Server_V2

jobs:
  build:
    name: CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Create application.yml on dev
        run: |
          mkdir ./src/main/resources
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_YML }}" >> ./src/main/resources/application.yml
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy script
        run: cp ./deploy-dev.sh ./deploy

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Deploy
        run: |
          aws deploy create-deployment \
          --application-name dotori-codedeploy \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name dotori-deploy-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=dotori-deploy-bucket,bundleType=zip,key=Bitgouel_Server/$GITHUB_SHA.zip \
          --region ap-northeast-2 \