name: Java CICD with Gradle

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create application.yml
        run: |
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_YML }}" >> ./src/main/resources/application.yml   

      - name: Create application-prod.yml
        run: |
          touch ./src/main/resources/application-prod.yml
          echo "${{ secrets.APPLICATION_PROD_YML }}" >> ./src/main/resources/application-prod.yml

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Pull Docker image
        run: sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/dotori

      - name: Delete Old docker container
        run: sudo docker rm -f dotori || true

      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name dotori ${{secrets.DOCKERHUB_USERNAME}}/dotori