name: Java CICD with Gradle

on:
  push:
    branches:
      - 'develop'

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Pull Docker image
        run: sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/dotori-dev

      - name: Docker stop container
        run: sudo docker stop dotori-dev 2>/dev/null || true

      - name: Run Docker Container
        run: sudo docker run --name dotori-dev --rm -d -p 8080:8080 ${{secrets.DOCKERHUB_USERNAME}}/dotori-dev

      - name: Delete old docker images
        run: sudo docker system prune -f